# Generated by Django 5.0.7 on 2024-07-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0003_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('exchange', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('sector_key', models.CharField(blank=True, max_length=100, null=True)),
                ('sector_display', models.CharField(blank=True, max_length=250, null=True)),
                ('industry_key', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_display', models.CharField(blank=True, max_length=250, null=True)),
                ('fulltime_employees', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
            },
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
