# Generated by Django 5.0.7 on 2024-07-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0004_stock_delete_destination'),
    ]

    operations = [
        migrations.RunSQL(
            sql="SELECT 1 FROM stock LIMIT 1;",
            reverse_sql="",
        ),
    ]
