# Generated by Django 5.0.7 on 2024-08-14 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0005_auto_20240722_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=255)),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOfficer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('year_born', models.IntegerField(blank=True, null=True)),
                ('exercised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unexercised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_pay', models.IntegerField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_management.stock')),
            ],
            options={
                'db_table': 'company_officer',
            },
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('year', models.DateField()),
                ('metric_type', models.CharField(max_length=50)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_management.stock')),
            ],
            options={
                'verbose_name': 'Financial Data',
                'verbose_name_plural': 'Financial Data',
                'db_table': 'financial_data',
            },
        ),
        migrations.AddConstraint(
            model_name='companyofficer',
            constraint=models.CheckConstraint(check=models.Q(('id__gte', 0)), name='company_officer_id_gte_0'),
        ),
        migrations.AlterUniqueTogether(
            name='financialdata',
            unique_together={('stock', 'symbol', 'year', 'metric_type')},
        ),
    ]
