# Generated by Django 5.0.7 on 2024-08-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0006_message_companyofficer_financialdata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(('email_id__isnull', False)), name='email_id_not_null'),
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
